name: Minecraft PC Data Dumper

on:
  workflow_dispatch:
    inputs:
      minecraft-version:
        description: 'Version of minecraft to dump data from'
        default: '1.16.5'
        required: true

jobs:
    dump-burger:
      runs-on: ubuntu-latest
      steps:
      - name: Setup Node
        uses: actions/setup-node@v2
        with:
          node-version: '15'
      - name: Setup Java
        uses: actions/setup-java@v1.4.3
        with:
          java-version: '17'
      - name: Setup Python
        uses: actions/setup-python@v2.2.2
      - name: Clone Repos
        run: |
            mkdir code && cd code
            git clone https://github.com/Pokechu22/Burger
            git clone https://github.com/PrismarineJS/burger-extractor
      - name: Run Burger
        run: |
            cd code/Burger
            pip install jawa six
            python3 munch.py --download ${{ github.event.inputs.minecraft-version }} --output ../burger.json
      - name: Run Burger-Extractor
        run: |
            cd code/burger-extractor
            npm i
            cd src
            node . ../burger.json ${{ github.event.inputs.minecraft-version }}
      - name: Save to Artifact
        uses: actions/upload-artifact@v2
        with:
          name: data
          path: code/burger-extractor/out/
          
    turbo-invention: # adds data to items.json from burger
      runs-on: ubuntu-latest
      needs:
      - dump-burger
      steps:
      - name: Setup Node
        uses: actions/setup-node@v2
        with:
          node-version: '15'
      - name: Clone Repos
        run: |
            mkdir code && cd code
            git clone https://github.com/u9g/turbo-invention
      - name: Download a Build Artifact
        uses: actions/download-artifact@v2.0.9
        with:
          name: data
          path: code/turbo-invention/
      - name: Run turbo-invention
        run: |
            cd code/turbo-invention
            node .
      - name: Save to Artifact
        uses: actions/upload-artifact@v2
        with:
          name: data
          path: code/turbo-invention/items.json
    minecraft-jar-extractor:
      runs-on: ubuntu-latest
      steps:
      - name: Setup Node
        uses: actions/setup-node@v2
        with:
          node-version: '15'
      - name: Setup Java
        uses: actions/setup-java@v1.4.3
        with:
          java-version: '17'
      - name: Clone Repos
        run: | # git clone https://github.com/PrismarineJS/minecraft-jar-extractor
            mkdir out && mkdir code && cd code
            git clone https://github.com/PrismarineJS/minecraft-jar-extractor/
            cd minecraft-jar-extractor
      - name: Make language.json
        run: |
            cd code/minecraft-jar-extractor
            npm i
            node lang.js 1.16.5 out-lang temp-lang
            mv out-lang/1.16.5/en_us.json ../../out/language.json
      - name: Make blockLoot.json & entityLoot.json
        run: |
            cd code/minecraft-jar-extractor
            node extract_datafolder.js 1.16.5 out-data temp-data
            node extract_lootTables.js 1.16.5 out-data temp-loottables
            mv temp-loottables/data/pc/1.16.5/blockLoot.json ../../out/blockLoot.json
            mv temp-loottables/data/pc/1.16.5/entityLoot.json ../../out/entityLoot.json
      - name: Save to Artifact
        uses: actions/upload-artifact@v2
        with:
          name: data
          path: out
    patch-jar-output:
      runs-on: ubuntu-latest
      needs:
      - minecraft-jar-extractor
      - dump-burger
      steps:
      - name: Setup Node
        uses: actions/setup-node@v2
        with:
          node-version: '15'
      - name: Setup Java
        uses: actions/setup-java@v1.4.3
        with:
          java-version: '17'
      - name: Clone Repos
        run: |
            mkdir code && cd code
            git clone https://github.com/PrismarineJS/minecraft-jar-extractor/
            cd minecraft-jar-extractor
      - name: Download a Build Artifact
        uses: actions/download-artifact@v2.0.9
        with:
          name: data
          path: code/minecraft-jar-extractor/
      - name: Run minecraft-jar-extractor
        run: |
            cd code/minecraft-jar-extractor
            npm i
            node extract_datafolder.js ${{ github.event.inputs.minecraft-version }} out temp
            node patch_states.js ${{ github.event.inputs.minecraft-version }} blocks.json
            node extract_block_lootTables.js . ../out/${{ github.event.inputs.minecraft-version }}/
      - name: Save to Artifact
        uses: actions/upload-artifact@v2
        with:
          name: data
          path: code/minecraft-jar-extractor/blocks.json
    make-pr:
      runs-on: ubuntu-latest
      needs: 
        - turbo-invention
        - patch-jar-output
      steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          token: ${{ secrets.PAT_PASSWORD }}
          repository: PrismarineJS/minecraft-data
      - name: Download a Build Artifact
        uses: actions/download-artifact@v2.0.9
        with:
          name: data
          path: data/pc/${{ github.event.inputs.minecraft-version }}/
      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v3
        with:
            commit-message: Add data from ${{ github.event.inputs.minecraft-version }}
            title: Add data from ${{ github.event.inputs.minecraft-version }}
            body: |
              Auto-generated by a GH workflow
            branch: add-${{ github.event.inputs.minecraft-version }}-data
            token: ${{ secrets.PAT_PASSWORD }}
