name: Minecraft PC Data Dumper

on:
  workflow_dispatch:
    inputs:
      minecraft-version:
        description: 'Version of minecraft to dump data from'
        default: '1.18'
        required: true

jobs:
    minecraft-data-generator:
      runs-on: ubuntu-latest
      steps:
      - name: Setup Node
        uses: actions/setup-node@v2
        with:
          node-version: '15'
      - name: Setup Java
        uses: actions/setup-java@v1.4.3
        with:
          java-version: '17'
      - name: Setup Python
        uses: actions/setup-python@v2.2.2
      - name: Clone Repos
        run: |
            mkdir code && cd code
            git clone https://github.com/u9g/minecraft-data-generator-server .
            chmod +x gradlew
            ./gradlew runServer
            ls -R .
      - name: Save to Artifact
        uses: actions/upload-artifact@v2
        with:
          name: data
          path: code/run/minecraft-data
    make-pr:
      runs-on: ubuntu-latest
      needs: 
        - minecraft-data-generator
      steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          token: ${{ secrets.PAT_PASSWORD }}
          repository: PrismarineJS/minecraft-data
      - name: Download a Build Artifact
        uses: actions/download-artifact@v2.0.9
        with:
          name: data
          path: data/pc/${{ github.event.inputs.minecraft-version }}/
      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v3
        with:
            commit-message: Add data from ${{ github.event.inputs.minecraft-version }}
            title: Add data from ${{ github.event.inputs.minecraft-version }}
            body: |
              Auto-generated by a GH workflow
            branch: add-${{ github.event.inputs.minecraft-version }}-data
            token: ${{ secrets.PAT_PASSWORD }}
